### ISSUE TITLE
Embed networks into user payload?

### ISSUE THREAD

**Issue by victor-nitu** [tenders-exposed/elvis-backend#20]
We can't populate the `user.networks` relationship on the frontend model. I assume it needs a serializer on the API side?

**Comment by georgiana-b** [comment]
No, the route GET `/api/v1/networks/{network_id}` sent with `X-User-Email` and `X-User-Token` will show that user's networks because each user can only see her/his networks. So, that's how you get them. 

The index payload contains only a summary of the networks _not_ the entire graph. For that, you have to use GET `/api/v1/networks/{network_id}` which is visible to anyone.

If you are not happy with this, feel free to propose a change of specs and reopen this.
